name: Github-Conext-Informations

on:
  push:
   
jobs:
   run_github-conext:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: GitHub Context Information
          run: echo '${{ toJSON(github) }}' | jq
    